routes/web.php
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);

    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

});

      //khusus READ ADMIN
        Route::get('/tanaman', 'KelolaTanamenController@tanaman');
        Route::get('/sensor', 'SensorsController@sensor');
        Route::get('/admingrafik', 'SensorsController@admingrafik');
        Route::get('/perangkat', 'perangkatsController@perangkat');
        Route::get('/manajemenpohonbicara', 'KelolaTanamenController@manajemenpohonbicara');
        Route::get('/showadmin', 'KelolaTanamenController@showadmin');;

// Pendaftaran online JerbeeUmroh
Route::get('/pendaftarans/register',[
    'as' => 'pendaftarans.register',
    'uses' => 'PendaftaransController@register'
]);
Route::post('pendaftarans/registerstore', 'PendaftaransController@registerstore');
/*
|--------------------------------------------------------------------------
| Pendaftaran Routes
|--------------------------------------------------------------------------
*/
 Route::resource('pendaftarans', 'PendaftaransController', ['except' => ['show']]);
        Route::post('pendaftarans/search', [
              'as' => 'pendaftarans.search',
              'uses' => 'PendaftaransController@search'
        ]);
        Route::get('/pendaftarans/{id}/verify',[
                'as' => 'pendaftarans.verify',
                'uses' => 'PendaftaransController@verify'
        ]);
        Route::post('pendaftarans/store_verify', 'PendaftaransController@store_verify');
  });


Route::resource('kelola_tanamen', 'KelolaTanamenController');
Route::post('kelola_tanamen/search', [
    'as' => 'kelola_tanamen.search',
    'uses' => 'KelolaTanamenController@search'
]);
Route::get('pohonbicara', 'KelolaTanamenController@pohonbicara');

Route::resource('sensors', 'SensorsController', ['except' => ['show']]);
Route::post('sensors/search', [
    'as' => 'sensors.search',
    'uses' => 'SensorsController@search'
]);
Route::get('grafik', 'SensorsController@grafik');
Route::get('grafik_waktu', 'SensorsController@grafik_waktu');
Route::get('grafikhari', 'SensorsController@grafikhari');
Route::get('grafikhari2', 'SensorsController@grafikhari2');
Route::get('grafikbulan', 'SensorsController@grafikbulan');
Route::get('grafikbulan2', 'SensorsController@grafikbulan2');
Route::get('grafiktahun', 'SensorsController@grafiktahun');
Route::get('grafiktahun2', 'SensorsController@grafiktahun2');

Route::resource('perangkats', 'PerangkatsController');
Route::post('perangkats/search', [
    'as' => 'perangkats.search',
    'uses' => 'PerangkatsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeSuhu Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_suhus', 'RangeSuhusController', ['except' => ['show']]);
Route::post('range_suhus/search', [
    'as' => 'range_suhus.search',
    'uses' => 'RangeSuhusController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeKelembapan Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_kelembapans', 'RangeKelembapansController', ['except' => ['show']]);
Route::post('range_kelembapans/search', [
    'as' => 'range_kelembapans.search',
    'uses' => 'RangeKelembapansController@search'
]);

/*
|--------------------------------------------------------------------------
| RangePhtanah Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_phtanahs', 'RangePhtanahsController', ['except' => ['show']]);
Route::post('range_phtanahs/search', [
    'as' => 'range_phtanahs.search',
    'uses' => 'RangePhtanahsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeCahaya Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_cahayas', 'RangeCahayasController', ['except' => ['show']]);
Route::post('range_cahayas/search', [
    'as' => 'range_cahayas.search',
    'uses' => 'RangeCahayasController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStopword Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stopwords', 'NlpStopwordsController', ['except' => ['show']]);
Route::post('nlp_stopwords/search', [
    'as' => 'nlp_stopwords.search',
    'uses' => 'NlpStopwordsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStemquestion Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stemquestions', 'NlpStemquestionsController', ['except' => ['show']]);
Route::post('nlp_stemquestions/search', [
    'as' => 'nlp_stemquestions.search',
    'uses' => 'NlpStemquestionsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpPertanyaanuser Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_pertanyaanusers', 'NlpPertanyaanusersController', ['except' => ['show']]);
Route::post('nlp_pertanyaanusers/search', [
    'as' => 'nlp_pertanyaanusers.search',
    'uses' => 'NlpPertanyaanusersController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpKatadasar Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_katadasars', 'NlpKatadasarsController', ['except' => ['show']]);
Route::post('nlp_katadasars/search', [
    'as' => 'nlp_katadasars.search',
    'uses' => 'NlpKatadasarsController@search'
]);

/*
|--------------------------------------------------------------------------
| SensorChat Routes
|--------------------------------------------------------------------------
*/

Route::resource('sensor_chats', 'SensorChatsController', ['except' => ['show']]);
Route::post('sensor_chats/search', [
    'as' => 'sensor_chats.search',

app/Models/Perangkat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Sensor;
use App\Models\User;

class Perangkat extends Model
{
    public $table = "perangkats";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'id',
		'user_id',
		'platform',
		'origin',
		'content',
		'keterangan',
        'tanaman_id',
        'notifikasi',
        'sent_chatbot',
        'last_answer',
        'notifikasi_suhu',
        'notifikasi_tanah',
        'notifikasi_cahaya',
        'notifikasi_kelembapan'
    
];

    public static $rules = [
        // create rules
    ];
   
   public function kelolaSensor()
    {
        return $this->hasMany(Sensor::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }


}

app/Http/Controllers/PerangkatsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\PerangkatService;
use App\Http\Requests\PerangkatCreateRequest;
use App\Http\Requests\PerangkatUpdateRequest;

class PerangkatsController extends Controller
{
    public function __construct(PerangkatService $perangkat_service)
    {
        $this->service = $perangkat_service;
    }

    public function index(Request $request)
    {
        $perangkats = $this->service->paginated();
        return view('perangkats.index')->with('perangkats', $perangkats);
    }

    //fungsi untuk admin
    public function perangkat(Request $request)
    {
        $perangkats = $this->service->paginated();
        return view('perangkats.index')->with('perangkats', $perangkats);
    }


   
    public function search(Request $request)
    {
        $perangkats = $this->service->search($request->search);
        return view('perangkats.index')->with('perangkats', $perangkats);
    }


    public function create()
    {
        return view('perangkats.create');
    }

    
    public function store(PerangkatCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('perangkats.index'))->with('message', 'Successfully created');
        }

        return redirect(route('perangkats.index'))->with('message', 'Failed to create');
    }

    
    public function show($id)
    {
        $perangkat = $this->service->find($id);
        return view('perangkats.show')->with('perangkat', $perangkat);
    }

   
    public function edit($id)
    {
        $perangkat = $this->service->find($id);
        return view('perangkats.edit')->with('perangkat', $perangkat);
    }

  
    public function update(PerangkatUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
             return redirect(route('perangkats.index'))->with('message', 'Successfully update');
        }

        return back()->with('message', 'Failed to update');
    }

  
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('perangkats.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('perangkats.index'))->with('message', 'Failed to delete');
    }
}

resources/views/perangkats/create.blade.php
@extends('dashboard')

@section('content')
<div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right"></div>
            <h1 class="pull-left"><span class="fa fa-server"></span> Kelola Perangkat</h1>
            </div>
        </div>

<div class="row">
  <div class="col-md-6 raw-margin-bottom-24 raw-margin-left-24">
  	  {!! Form::open(['route' => 'perangkats.store', 'files' => true]) !!}
              {!! csrf_field() !!}

			<input type="hidden" name="user_id"  class="form-control" value="{{Auth::user()->id}}" required>
    		 <div class="raw-margin-top-24">
                  @input_maker_label('platform')
                  @input_maker_create('platform', ['type' => 'text'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('origin')
                  @input_maker_create('origin', ['type' => 'text'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('content')
                  @input_maker_create('content', ['type' => 'text'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('keterangan')
                  @input_maker_create('keterangan', ['type' => 'text'])
              </div>
             
              <div class="raw-margin-top-24">
                  <a class="btn btn-default pull-left" href="{!! route('perangkats.index') !!}">Cancel</a>
                  <button class="btn btn-primary pull-right" type="submit">Create</button>
              </div>
<br/></br/><br/></br/><br/></br/>
          {!! Form::close() !!}
      </div>


    </div>
</div>

</div>
@stop

resources/views/perangkats/edit.blade.php
@extends('dashboard')

@section('content')
<div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right"></div>
            <h1 class="pull-left"><span class="fa fa-server"></span> Kelola Perangkat</h1>
            </div>
        </div>
<div class="row">
  <div class="col-md-6 raw-margin-bottom-24 raw-margin-left-24">

    {!! Form::model($perangkat, ['route' => ['perangkats.update', $perangkat->id], 'method' => 'patch', 'files' =>true]) !!}
     {!! csrf_field() !!}    {!! method_field('PATCH') !!}

               
                     @form_maker_object($perangkat,[
                    'platform'=>['alt_name'=>'platform'],
                    'origin'=>['alt_name'=>'origin'],
                    'content'=>['alt_name'=>'content'],
                    'keterangan'=>['alt_name'=>'keterangan'],
                    ])
           
        <div class="raw-margin-top-24">
                      <a class="btn btn-default pull-left" href="{!! route('perangkats.index') !!}">Cancel</a>
                      <button class="btn btn-primary pull-right" type="submit">Save</button>
                  </div>

            {!! Form::close() !!}
          </div>
      </div>
  </div>

@stop

resources/views/perangkats/index.blade.php
@extends('dashboard')

@section('content')
<div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                 <form id="" class="pull-right raw-margin-top-24 raw-margin-left-24" method="post" action="/perangkats/search">
                    {!! csrf_field() !!}
                     <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                 {!! Form::close() !!}
                 <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('perangkats.create') !!}">Tambah</a>
                  </div>
            <h1 class="pull-left"><span class="fa fa-server"></span> Kelola Perangkat</h1>
            </div>
        </div>

     <div class="row">
        @if($perangkats->isEmpty())
            <div class="well text-center">No Perangakat found.</div>
        @else
    <div class="row raw-margin-top-24">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <th>Nama platform</th>
                    <th>Header Origin</th>
                    <th>Keterangan</th>
                    <th width="150px">Action</th>
                </thead>
                <tbody>
                @foreach($perangkats as $perangkat)
                    <tr>
                        <td>{{ $perangkat->platform }}</td>
                        <td>{{ $perangkat->origin }}</td>
                        <td>{{ $perangkat->keterangan }}</td>
                        <td>
                        
                        <a style="margin:1px;" class="btn btn-warning btn-xs pull-right raw-margin-right-16" href="{!! route('perangkats.edit', [$perangkat->id]) !!}"><span class="fa fa-edit"></span> Ubah</a>
                        <form method="post" action="{!! route('perangkats.destroy', [$perangkat->id]) !!}">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                        <button style="margin:1px;" class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Yakin untuk menghapus ?')"><i class="fa fa-trash"></i> Hapus</button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="row">
              
            </div>
        @endif
    </div>
</div>
@stop

resources/views/perangkats/show.blade.php
<div class="container">

    <!-- Put fields here -->

</div>