routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Non protected/public routes
Route::get('/', 'WelcomeController@index');

Route::get('antares', 'AntaresController@index');

Route::get('getantares/{id}', 'KelolaTanamenController@antares');

// Login Logout
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);

    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

});

      //khusus READ ADMIN
        Route::get('/tanaman', 'KelolaTanamenController@tanaman');
        Route::get('/sensor', 'SensorsController@sensor');
        Route::get('/admingrafik', 'SensorsController@admingrafik');
        Route::get('/perangkat', 'perangkatsController@perangkat');
        Route::get('/manajemenpohonbicara', 'KelolaTanamenController@manajemenpohonbicara');
        Route::get('/showadmin', 'KelolaTanamenController@showadmin');;

// Pendaftaran online JerbeeUmroh
Route::get('/pendaftarans/register',[
    'as' => 'pendaftarans.register',
    'uses' => 'PendaftaransController@register'
]);
Route::post('pendaftarans/registerstore', 'PendaftaransController@registerstore');
/*
|--------------------------------------------------------------------------
| Pendaftaran Routes
|--------------------------------------------------------------------------
*/
 Route::resource('pendaftarans', 'PendaftaransController', ['except' => ['show']]);
        Route::post('pendaftarans/search', [
              'as' => 'pendaftarans.search',
              'uses' => 'PendaftaransController@search'
        ]);
        Route::get('/pendaftarans/{id}/verify',[
                'as' => 'pendaftarans.verify',
                'uses' => 'PendaftaransController@verify'
        ]);
        Route::post('pendaftarans/store_verify', 'PendaftaransController@store_verify');
  });


Route::resource('kelola_tanamen', 'KelolaTanamenController');
Route::post('kelola_tanamen/search', [
    'as' => 'kelola_tanamen.search',
    'uses' => 'KelolaTanamenController@search'
]);
Route::get('pohonbicara', 'KelolaTanamenController@pohonbicara');

Route::resource('sensors', 'SensorsController', ['except' => ['show']]);
Route::post('sensors/search', [
    'as' => 'sensors.search',
    'uses' => 'SensorsController@search'
]);
Route::get('grafik', 'SensorsController@grafik');
Route::get('grafik_waktu', 'SensorsController@grafik_waktu');
Route::get('grafikhari', 'SensorsController@grafikhari');
Route::get('grafikhari2', 'SensorsController@grafikhari2');
Route::get('grafikbulan', 'SensorsController@grafikbulan');
Route::get('grafikbulan2', 'SensorsController@grafikbulan2');
Route::get('grafiktahun', 'SensorsController@grafiktahun');
Route::get('grafiktahun2', 'SensorsController@grafiktahun2');

Route::resource('perangkats', 'PerangkatsController');
Route::post('perangkats/search', [
    'as' => 'perangkats.search',
    'uses' => 'PerangkatsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeSuhu Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_suhus', 'RangeSuhusController', ['except' => ['show']]);
Route::post('range_suhus/search', [
    'as' => 'range_suhus.search',
    'uses' => 'RangeSuhusController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeKelembapan Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_kelembapans', 'RangeKelembapansController', ['except' => ['show']]);
Route::post('range_kelembapans/search', [
    'as' => 'range_kelembapans.search',
    'uses' => 'RangeKelembapansController@search'
]);

/*
|--------------------------------------------------------------------------
| RangePhtanah Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_phtanahs', 'RangePhtanahsController', ['except' => ['show']]);
Route::post('range_phtanahs/search', [
    'as' => 'range_phtanahs.search',
    'uses' => 'RangePhtanahsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeCahaya Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_cahayas', 'RangeCahayasController', ['except' => ['show']]);
Route::post('range_cahayas/search', [
    'as' => 'range_cahayas.search',
    'uses' => 'RangeCahayasController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStopword Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stopwords', 'NlpStopwordsController', ['except' => ['show']]);
Route::post('nlp_stopwords/search', [
    'as' => 'nlp_stopwords.search',
    'uses' => 'NlpStopwordsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStemquestion Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stemquestions', 'NlpStemquestionsController', ['except' => ['show']]);
Route::post('nlp_stemquestions/search', [
    'as' => 'nlp_stemquestions.search',
    'uses' => 'NlpStemquestionsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpPertanyaanuser Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_pertanyaanusers', 'NlpPertanyaanusersController', ['except' => ['show']]);
Route::post('nlp_pertanyaanusers/search', [
    'as' => 'nlp_pertanyaanusers.search',
    'uses' => 'NlpPertanyaanusersController@search'
]);

/*

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Content;

class Topic extends Model
{
    public $table = "topics";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        		'id',
		'name',
		'description',
		'body',
		'user_id',
		'status',

    ];

    public static $rules = [
        // create rules
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function contents()
    {
        return $this->hasMany(Content::class);
    }
    // Topic

}

app/Http/Controllers/TopicsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\TopicService;
use App\Http\Requests\TopicRequest;

class TopicsController extends Controller
{
    public function __construct(TopicService $topicService)
    {
        $this->service = $topicService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $topics = $this->service->paginated();
        return view('topics.index')->with('topics', $topics);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $topics = $this->service->search($request->search);
        return view('topics.index')->with('topics', $topics);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\TopicRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TopicRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('topics.index'))->with('message', 'Successfully created');
        }

        return redirect(route('topics.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the topics.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $topic = $this->service->find($id);
        return view('topics.show')->with('topic', $topic);
    }

    /**
     * Show the form for editing the topics.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $topic = $this->service->find($id);
        return view('topics.edit')->with('topic', $topic);
    }

    /**
     * Update the topics in storage.
     *
     * @param  \Illuminate\Http\TopicRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TopicRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return redirect(route('topics.index'))->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the topics from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('topics.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('topics.index'))->with('message', 'Failed to delete');
    }
}

resources/views/topics/create.blade.php
@extends('dashboard')

@section('content')

<div class="row">
    <div class="col-md-12">
        <h1>Topics : Create</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6 raw-margin-bottom-24">

            {!! Form::open(['route' => 'topics.store']) !!}
                {!! csrf_field() !!}

                @form_maker_table("topics")

                <div class="raw-margin-top-24">
                    <a class="btn btn-default pull-left" href="{{ URL::previous() }}">Cancel</a>
                    <button class="btn btn-primary pull-right" type="submit">Create</button>
                </div>

            {!! Form::close() !!}
        </div>

    </div>
</div>

@stop

resources/views/topics/edit.blade.php
@extends('dashboard')

@section('content')

  <div class="row">
      <div class="col-md-12">
          <h1>Topic : Edit</h1>
      </div>
  </div>

  <div class="row">
      <div class="col-md-6 raw-margin-bottom-24">
          <div>
              {!! Form::model($topic, ['route' => ['topics.update', $topic->id], 'method' => 'patch']) !!}
                  {!! csrf_field() !!}
                  {!! method_field('PATCH') !!}

                  @form_maker_object($topic, FormMaker::getTableColumns('topics'))

                  <div class="raw-margin-top-24">
                      <a class="btn btn-default" href="{{ URL::previous() }}">Cancel</a>
                      <button class="btn btn-primary pull-right" type="submit">Save</button>
                  </div>

            {!! Form::close() !!}
          </div>
      </div>
  </div>

@stop

resources/views/topics/index.blade.php
@extends('dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => 'topics.search','class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
              {!! csrf_field() !!}
              <input class="form-control form-inline pull-right" name="search" placeholder="Search">
            {!! Form::close() !!}
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('topics.create') !!}">Add New</a>
            <h1 class="pull-left">Topics</h1>
        </div>
    </div>
    <div class="row raw-margin-top-24">
        <div class="col-md-12">
            @if($topics->isEmpty())
                <div class="well text-center">No topics found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th width="200px" class="text-right">Action</th>
                    </thead>
                    <tbody>
                    @foreach($topics as $topic)
                        <tr>
                            <td>
                                {{ $topic->name }}
                            </td>
                            <td>
                                <form method="post" action="{!! route('topics.destroy', [$topic->id]) !!}">
                                    {!! csrf_field() !!}
                                    {!! method_field('DELETE') !!}
                                    <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this topic?')"><i class="fa fa-trash"></i> Delete</button>
                                </form>
                                <a class="btn btn-warning btn-xs" href="{!! route('topics.show', [$topic->id]) !!}"><i class="fa fa-search"></i> Show</a>
                                <a class="btn btn-warning btn-xs" href="{!! route('topics.edit', [$topic->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="row text-center">
                    {!! $topics; !!}
                </div>
            @endif
        </div>
    </div>

@stop

resources/views/topics/show.blade.php
@extends('dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12">
        <h1>{{ $topic->name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        Modify this page for detailed show/info.
        </div>
    </div>
    {!! link_to(URL::previous(), 'Back', ['class' => 'btn btn-default btn-primary pull-right']) !!}
@stop