routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Non protected/public routes
Route::get('/', 'WelcomeController@index');

Route::get('antares', 'AntaresController@index');

Route::get('getantares/{id}', 'KelolaTanamenController@antares');

// Login Logout
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);

    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

});

      //khusus READ ADMIN
        Route::get('/tanaman', 'KelolaTanamenController@tanaman');
        Route::get('/sensor', 'SensorsController@sensor');
        Route::get('/admingrafik', 'SensorsController@admingrafik');
        Route::get('/perangkat', 'perangkatsController@perangkat');
        Route::get('/manajemenpohonbicara', 'KelolaTanamenController@manajemenpohonbicara');
        Route::get('/showadmin', 'KelolaTanamenController@showadmin');;

// Pendaftaran online JerbeeUmroh
Route::get('/pendaftarans/register',[
    'as' => 'pendaftarans.register',
    'uses' => 'PendaftaransController@register'
]);
Route::post('pendaftarans/registerstore', 'PendaftaransController@registerstore');
/*
|--------------------------------------------------------------------------
| Pendaftaran Routes
|--------------------------------------------------------------------------
*/
 Route::resource('pendaftarans', 'PendaftaransController', ['except' => ['show']]);
        Route::post('pendaftarans/search', [
              'as' => 'pendaftarans.search',
              'uses' => 'PendaftaransController@search'
        ]);
        Route::get('/pendaftarans/{id}/verify',[
                'as' => 'pendaftarans.verify',
                'uses' => 'PendaftaransController@verify'
        ]);
        Route::post('pendaftarans/store_verify', 'PendaftaransController@store_verify');
  });


Route::resource('kelola_tanamen', 'KelolaTanamenController');
Route::post('kelola_tanamen/search', [
    'as' => 'kelola_tanamen.search',
    'uses' => 'KelolaTanamenController@search'
]);
Route::get('pohonbicara', 'KelolaTanamenController@pohonbicara');

Route::resource('sensors', 'SensorsController', ['except' => ['show']]);
Route::post('sensors/search', [
    'as' => 'sensors.search',
    'uses' => 'SensorsController@search'
]);
Route::get('grafik', 'SensorsController@grafik');
Route::get('grafik_waktu', 'SensorsController@grafik_waktu');
Route::get('grafikhari', 'SensorsController@grafikhari');
Route::get('grafikhari2', 'SensorsController@grafikhari2');
Route::get('grafikbulan', 'SensorsController@grafikbulan');
Route::get('grafikbulan2', 'SensorsController@grafikbulan2');
Route::get('grafiktahun', 'SensorsController@grafiktahun');
Route::get('grafiktahun2', 'SensorsController@grafiktahun2');

Route::resource('perangkats', 'PerangkatsController');
Route::post('perangkats/search', [
    'as' => 'perangkats.search',
    'uses' => 'PerangkatsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeSuhu Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_suhus', 'RangeSuhusController', ['except' => ['show']]);
Route::post('range_suhus/search', [
    'as' => 'range_suhus.search',
    'uses' => 'RangeSuhusController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeKelembapan Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_kelembapans', 'RangeKelembapansController', ['except' => ['show']]);
Route::post('range_kelembapans/search', [
    'as' => 'range_kelembapans.search',
    'uses' => 'RangeKelembapansController@search'
]);

/*
|--------------------------------------------------------------------------
| RangePhtanah Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_phtanahs', 'RangePhtanahsController', ['except' => ['show']]);
Route::post('range_phtanahs/search', [
    'as' => 'range_phtanahs.search',
    'uses' => 'RangePhtanahsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeCahaya Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_cahayas', 'RangeCahayasController', ['except' => ['show']]);
Route::post('range_cahayas/search', [
    'as' => 'range_cahayas.search',
    'uses' => 'RangeCahayasController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStopword Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stopwords', 'NlpStopwordsController', ['except' => ['show']]);
Route::post('nlp_stopwords/search', [
    'as' => 'nlp_stopwords.search',
    'uses' => 'NlpStopwordsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStemquestion Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stemquestions', 'NlpStemquestionsController', ['except' => ['show']]);
Route::post('nlp_stemquestions/search', [
    'as' => 'nlp_stemquestions.search',
    'uses' => 'NlpStemquestionsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpPertanyaanuser Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_pertanyaanusers', 'NlpPertanyaanusersController', ['except' => ['show']]);
Route::post('nlp_pertanyaanusers/search', [
    'as' => 'nlp_pertanyaanusers.search',
    'uses' => 'NlpPertanyaanusersController@search'
]);

/*

resources/views/kelola_tanamen/create.blade.php
@extends('dashboard')

@section('content')
<div class="">
    {{ Session::get('message') }}
</div>

 <div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                  </div>
            <h1 class="pull-left"><span class="fa fa-tree"></span> Kelola Tanaman</h1>
            </div>
        </div>
  	  {!! Form::open(['route' => 'kelola_tanamen.store', 'files' => true]) !!}
              {!! csrf_field() !!}

			<input type="hidden" name="user_id"  class="form-control" value="{{Auth::user()->id}}" required>
    
              <div class="raw-margin-top-24">
                  @input_maker_label('Jenis Tanaman')
                  @input_maker_create('jenis_tanaman', ['type' => 'string'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('Nama Tanaman')
                  @input_maker_create('nama_tanaman', ['type' => 'string'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('Longitute')
                  @input_maker_create('longitute', ['type' => 'string'])
              </div>
              <div class="raw-margin-top-24">
                  @input_maker_label('Latitude *')
                  @input_maker_create('latitude', ['type' => 'text'])
              </div>
               <div class="raw-margin-top-24">
                  <label for="">Nama Perangkat</label>
                    <select class="form-control input-sm" name="perangkat_id"> 
                         @foreach($perangkats as $perangkat)
                           <option value="{{$perangkat->id}}">{{$perangkat->keterangan}}     </option>
                         @endforeach
                    </select>
              </div>
              <div class="raw-margin-top-24">
                <input type="file" name="foto">
              </div>
              <div class="raw-margin-top-24">
                  <a class="btn btn-default pull-left" href="{!! route('kelola_tanamen.index') !!}">Cancel</a>
                  <button class="btn btn-primary pull-right" type="submit">Create</button>
              </div>
<br/></br/><br/></br/><br/></br/>
          {!! Form::close() !!}
      </div>


    </div>
</div>

</div>
@stop

resources/views/kelola_tanamen/edit.blade.php
@extends('dashboard')

@section('content')
<div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                  </div>
            <h1 class="pull-left"><span class="fa fa-tree"></span> Kelola Tanaman</h1>
            </div>
        </div>

<div class="row">
  <div class="col-md-6 raw-margin-bottom-24 raw-margin-left-24">

    {!! Form::model($kelola_tanaman, ['route' => ['kelola_tanamen.update', $kelola_tanaman->id], 'method' => 'patch', 'files' =>true]) !!}
     {!! csrf_field() !!}    {!! method_field('PATCH') !!}

               
                     @form_maker_object($kelola_tanaman,[
                    'jenis_tanaman'=>['alt_name'=>'jenis_tanaman'],
                    'nama_tanaman'=>['alt_name'=>'nama_tanaman'],
                    'longitute'=>['alt_name'=>'Longitute'],
                    'latitude'=>['alt_name'=>'latitude'],
                    ])

                <div class="raw-margin-top-24">
                  <label for="">Nama Perangkat</label>
                    <select class="form-control input-sm" name="perangkat_id"> 
                         @foreach($perangkats as $perangkat)
                           <option value="{{$perangkat->id}}">{{$perangkat->keterangan}}     </option>
                         @endforeach
                    </select>
              </div><br>
			         <div class="form-group">
                       <label class="control-label" for="foto">Foto</label><br />
                       <img class="img-thumbnail" src="{{ url($kelola_tanaman->foto->url('thumb')) }}">
                       <input type="file" name="foto">
                     </div>

                  <div class="raw-margin-top-24">
                      <a class="btn btn-default pull-left" href="{!! route('kelola_tanamen.index') !!}">Cancel</a>
                      <button class="btn btn-primary pull-right" type="submit">Save</button>
                  </div>

            {!! Form::close() !!}
          </div>
      </div>
  </div>

@stop

resources/views/kelola_tanamen/index.blade.php
@extends('dashboard')

@section('content')
   <div class="row">
        <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
          {!! Form::open(['route' => 'kelola_tanamen.search','class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
            {!! csrf_field() !!}
            
          {!! Form::close() !!}
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('kelola_tanamen.create') !!}">Add New</a>
            <h1 class="pull-left"><span class="fa fa-tree"></span> Kelola Tanaman</h1>
        </div>
    </div>
<div class="container">
    <div class="row">
        @if($kelola_tanamen->isEmpty())
            <div class="well text-center">No pendaftarans found.</div>
        @else
    <div class="row raw-margin-top-24">
        <div class="col-md-11">
            <table class="display table table-striped" id="tabel">
                <thead>
                   <th> Foto</th>
                    <th>Jenis Tanaman</th> 
                    <th>Nama Tanaman</th>
                    <th>Longitute</th>
                    <th>Latitude</th>
                    <th>Aksi</th>
                </thead>
                <tbody>
                @foreach($kelola_tanamen as $kelola_tanaman)
                    <tr>
                         <td><img class="img-thumbnail" src="{{ url($kelola_tanaman->foto->url('thumb')) }}"></td>
                        <td>{{ $kelola_tanaman->jenis_tanaman }}</td>
                        <td>{{ $kelola_tanaman->nama_tanaman }}</td>
                        <td>{{ $kelola_tanaman->longitute }}</td>
                        <td>{{ $kelola_tanaman->latitude }}</td>
                       
             
                        <td>
                        <a style="margin:1px;" class="btn btn-warning btn-xs pull-right raw-margin-right-16" href="{!! route('kelola_tanamen.edit', [$kelola_tanaman->id]) !!}"><span class="fa fa-edit"></span> Ubah</a>
                        <form method="post" action="{!! route('kelola_tanamen.destroy', [$kelola_tanaman->id]) !!}">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                        <button style="margin:1px;" class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this user?')"><i class="fa fa-trash"></i> Hapus</button></td>
                     
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="row">
              
            </div>
        @endif
    </div>
</div>
</div>
@stop
@section('javascript')
<script type="text/javascript">
    $(document).ready( function () {
    $('.display').DataTable();
    } );
</script>
@stop

resources/views/kelola_tanamen/pohonbicara.blade.php
@extends('dashboard')

@section('content')
   <div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                  </div>
            <h1 class="pull-left"><span class="fa fa-laptop"></span> Manajemen Pohon Bicara</h1>
            </div>
        </div>
<div class="container">
    <div class="row">
        @if($kelola_tanamen->isEmpty())
            <div class="well text-center">No pendaftarans found.</div>
        @else
    <div class="row raw-margin-top-24">
        <div class="col-md-11">
            <table class="display table table-striped">
                <thead>
                    <th>Foto</th>
                    <th>Jenis Tanaman</th>
                    <th>Nama Tanaman</th>
                    <th width="290px">Action</th>
                </thead>
                <tbody>
                @foreach($kelola_tanamen as $kelola_tanaman)
                    <tr>
                        <td><img class="img-thumbnail" src="{{ url($kelola_tanaman->foto->url('thumb')) }}"></td>
                        <td>{{ $kelola_tanaman->jenis_tanaman }}</td>
                        <td>{{ $kelola_tanaman->nama_tanaman }}</td>
                        <td><a class="btn btn-warning btn-xs" href="{!! route('kelola_tanamen.show', [$kelola_tanaman->id]) !!}"><h5> Lihat Pohon Bicara</h5></a>
                        </td>

                       
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="row">
              
            </div>
        @endif
    </div>
</div>
</div>
@stop
@section('javascript')
<script type="text/javascript">
    $(document).ready( function () {
    $('.display').DataTable();
    } );
</script>
@stop