routes/web.php
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
// Regisration
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('activate', 'Auth\ActivateController@showActivate');
Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
Route::get('activate/token/{token}', 'Auth\ActivateController@activate');

// HARUS login / Authenticated Routes
Route::group(['middleware' => ['auth', 'active']], function () {
    // User stuff
    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::post('editmeta/{id}', 'SettingsController@updatemeta');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });
    // Dashboard
    Route::get('/dashboard', 'PagesController@dashboard');

    // Team
    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');


    // HARUS login, HARUS admin atau member
    Route::group(['middleware' => 'roles:admin|member'], function () {
        Route::resource('contents', 'ContentsController');
        Route::post('contents/search', [
            'as' => 'contents.search',
            'uses' => 'ContentsController@search'
        ]);
    });

    // HARUS login, HARUS admin
    Route::group(['middleware' => 'roles:admin'], function () {
      // Organization & References
      Route::resource('companies', 'CompaniesController');
      Route::post('companies/search', [
          'as' => 'companies.search',
          'uses' => 'CompaniesController@search'
      ]);

      // CMS
      Route::resource('topics', 'TopicsController');
      Route::post('topics/search', [
          'as' => 'topics.search',
          'uses' => 'TopicsController@search'
      ]);
      Route::resource('categories', 'CategoriesController');
      Route::post('categories/search', [
          'as' => 'categories.search',
          'uses' => 'CategoriesController@search'
      ]);
      Route::resource('offlinewriters', 'OfflineWritersController');
      Route::post('offlinewriters/search', [
          'as' => 'offlinewriters.search',
          'uses' => 'OfflineWritersController@search'
      ]);
      Route::resource('comments', 'CommentsController');
      Route::post('comments/search', [
          'as' => 'comments.search',
          'uses' => 'CommentsController@search'
      ]);
      // Log System
      Route::resource('logsystems', 'LogsystemsController');
      Route::post('logsystems/search', [
          'as' => 'logsystems.search',
          'uses' => 'LogsystemsController@search'
      ]);

    });

    // HARUS login, HARUS admin dan controllernya HARUS di /admin
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
        // User
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        // Roles
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

});

      //khusus READ ADMIN
        Route::get('/tanaman', 'KelolaTanamenController@tanaman');
        Route::get('/sensor', 'SensorsController@sensor');
        Route::get('/admingrafik', 'SensorsController@admingrafik');
        Route::get('/perangkat', 'perangkatsController@perangkat');
        Route::get('/manajemenpohonbicara', 'KelolaTanamenController@manajemenpohonbicara');
        Route::get('/showadmin', 'KelolaTanamenController@showadmin');;

// Pendaftaran online JerbeeUmroh
Route::get('/pendaftarans/register',[
    'as' => 'pendaftarans.register',
    'uses' => 'PendaftaransController@register'
]);
Route::post('pendaftarans/registerstore', 'PendaftaransController@registerstore');
/*
|--------------------------------------------------------------------------
| Pendaftaran Routes
|--------------------------------------------------------------------------
*/
 Route::resource('pendaftarans', 'PendaftaransController', ['except' => ['show']]);
        Route::post('pendaftarans/search', [
              'as' => 'pendaftarans.search',
              'uses' => 'PendaftaransController@search'
        ]);
        Route::get('/pendaftarans/{id}/verify',[
                'as' => 'pendaftarans.verify',
                'uses' => 'PendaftaransController@verify'
        ]);
        Route::post('pendaftarans/store_verify', 'PendaftaransController@store_verify');
  });


Route::resource('kelola_tanamen', 'KelolaTanamenController');
Route::post('kelola_tanamen/search', [
    'as' => 'kelola_tanamen.search',
    'uses' => 'KelolaTanamenController@search'
]);
Route::get('pohonbicara', 'KelolaTanamenController@pohonbicara');

Route::resource('sensors', 'SensorsController', ['except' => ['show']]);
Route::post('sensors/search', [
    'as' => 'sensors.search',
    'uses' => 'SensorsController@search'
]);
Route::get('grafik', 'SensorsController@grafik');
Route::get('grafik_waktu', 'SensorsController@grafik_waktu');
Route::get('grafikhari', 'SensorsController@grafikhari');
Route::get('grafikhari2', 'SensorsController@grafikhari2');
Route::get('grafikbulan', 'SensorsController@grafikbulan');
Route::get('grafikbulan2', 'SensorsController@grafikbulan2');
Route::get('grafiktahun', 'SensorsController@grafiktahun');
Route::get('grafiktahun2', 'SensorsController@grafiktahun2');

Route::resource('perangkats', 'PerangkatsController');
Route::post('perangkats/search', [
    'as' => 'perangkats.search',
    'uses' => 'PerangkatsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeSuhu Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_suhus', 'RangeSuhusController', ['except' => ['show']]);
Route::post('range_suhus/search', [
    'as' => 'range_suhus.search',
    'uses' => 'RangeSuhusController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeKelembapan Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_kelembapans', 'RangeKelembapansController', ['except' => ['show']]);
Route::post('range_kelembapans/search', [
    'as' => 'range_kelembapans.search',
    'uses' => 'RangeKelembapansController@search'
]);

/*
|--------------------------------------------------------------------------
| RangePhtanah Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_phtanahs', 'RangePhtanahsController', ['except' => ['show']]);
Route::post('range_phtanahs/search', [
    'as' => 'range_phtanahs.search',
    'uses' => 'RangePhtanahsController@search'
]);

/*
|--------------------------------------------------------------------------
| RangeCahaya Routes
|--------------------------------------------------------------------------
*/

Route::resource('range_cahayas', 'RangeCahayasController', ['except' => ['show']]);
Route::post('range_cahayas/search', [
    'as' => 'range_cahayas.search',
    'uses' => 'RangeCahayasController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStopword Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stopwords', 'NlpStopwordsController', ['except' => ['show']]);
Route::post('nlp_stopwords/search', [
    'as' => 'nlp_stopwords.search',
    'uses' => 'NlpStopwordsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpStemquestion Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_stemquestions', 'NlpStemquestionsController', ['except' => ['show']]);
Route::post('nlp_stemquestions/search', [
    'as' => 'nlp_stemquestions.search',
    'uses' => 'NlpStemquestionsController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpPertanyaanuser Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_pertanyaanusers', 'NlpPertanyaanusersController', ['except' => ['show']]);
Route::post('nlp_pertanyaanusers/search', [
    'as' => 'nlp_pertanyaanusers.search',
    'uses' => 'NlpPertanyaanusersController@search'
]);

/*
|--------------------------------------------------------------------------
| NlpKatadasar Routes
|--------------------------------------------------------------------------
*/

Route::resource('nlp_katadasars', 'NlpKatadasarsController', ['except' => ['show']]);
Route::post('nlp_katadasars/search', [
    'as' => 'nlp_katadasars.search',
    'uses' => 'NlpKatadasarsController@search'
]);

/*
|--------------------------------------------------------------------------
| SensorChat Routes
|--------------------------------------------------------------------------
*/

Route::resource('sensor_chats', 'SensorChatsController', ['except' => ['show']]);
Route::post('sensor_chats/search', [
    'as' => 'sensor_chats.search',

app/Models/NlpKatadasar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class NlpKatadasar extends Model
{
    public $table = "nlp_katadasars";

    public $primaryKey = "id";
    // public $primaryKey = "id_katadasar";

    public $timestamps = true;

    public $fillable = [
		// 'id_katadasar',
		'katadasar',
		'tipe_katadasar',
    
];

    public static $rules = [
        // create rules
    ];
    // NlpKatadasar 
}

app/Http/Controllers/NlpKatadasarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\NlpKatadasarService;
use App\Http\Requests\NlpKatadasarCreateRequest;
use App\Http\Requests\NlpKatadasarUpdateRequest;

class NlpKatadasarsController extends Controller
{
    public function __construct(NlpKatadasarService $nlp_katadasar_service)
    {
        $this->service = $nlp_katadasar_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $nlp_katadasars = $this->service->paginated();
        return view('nlp_katadasars.index')->with('nlp_katadasars', $nlp_katadasars);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $nlp_katadasars = $this->service->search($request->search);
        return view('nlp_katadasars.index')->with('nlp_katadasars', $nlp_katadasars);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('nlp_katadasars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\NlpKatadasarCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NlpKatadasarCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('nlp_katadasars.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('nlp_katadasars.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the nlp_katadasar.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $nlp_katadasar = $this->service->find($id);
        return view('nlp_katadasars.show')->with('nlp_katadasar', $nlp_katadasar);
    }

    /**
     * Show the form for editing the nlp_katadasar.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $nlp_katadasar = $this->service->find($id);
        return view('nlp_katadasars.edit')->with('nlp_katadasar', $nlp_katadasar);
    }

    /**
     * Update the nlp_katadasars in storage.
     *
     * @param  \Illuminate\Http\NlpKatadasarUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NlpKatadasarUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the nlp_katadasars from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('nlp_katadasars.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('nlp_katadasars.index'))->with('message', 'Failed to delete');
    }
}

resources/views/nlp_katadasars/create.blade.php
@extends('dashboard')

@section('content')
<div class="">
    {{ Session::get('message') }}
</div>

 <div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                  </div>
            <h1 class="pull-left"><span class="fa fa-tree"></span> NLP Kata Dasar</h1>
            </div>
        </div>

<div class="container">

    {!! Form::open(['route' => 'nlp_katadasars.store']) !!}

    @form_maker_table("nlp_katadasars")

    {!! Form::submit('Save') !!}

    {!! Form::close() !!}

</div>
@stop

resources/views/nlp_katadasars/edit.blade.php
@extends('dashboard')

@section('content')
<div class="row">
            <div class="col-md-12" style="background:#eee; border-radius:0 0 14px 14px; margin:4px;">
                 <div class="pull-right">
                  </div>
            <h1 class="pull-left"><span class="fa fa-tree"></span> Edit NLP Kata Dasar</h1>
            </div>
        </div>

<div class="row">
  <div class="col-md-6 raw-margin-bottom-24 raw-margin-left-24">

	<div class="">
	    {{ Session::get('message') }}
	</div>

	<div class="container">

	    {!! Form::model($nlp_katadasar, ['route' => ['nlp_katadasars.update', $nlp_katadasar->id], 'method' => 'patch']) !!}

	    @form_maker_object($nlp_katadasar, FormMaker::getTableColumns('nlp_katadasars'))

	    {!! Form::submit('Update') !!}

	    {!! Form::close() !!}
	</div>
      </div>
  </div>

@stop

resources/views/nlp_katadasars/index.blade.php
@extends('dashboard')
@section('content')
<div class="container">

    <div class="">
        {{ Session::get('message') }}
    </div>

    <div class="row">
        <div class="" >
            {!! Form::open(['route' => 'nlp_katadasars.search', 'class' => 'pull-right raw-margin-top-24 raw-margin-left-24']) !!}
            <input class="form-control form-inline pull-right" name="search" placeholder="Search">
            {!! Form::close() !!}
        </div>
       
        <h1 class="pull-left">Nlp Kata dasar</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('nlp_katadasars.create') !!}">Add New</a>
    </div>

    <div class="row">
        @if($nlp_katadasars->isEmpty())
            <div class="well text-center">Kata Dasar tidak ditemukan</div>
        @else
            <table class="table">
                <thead>
                    <th>Kata Dasar</th>
                    <th>Tipe Kata Dasar</th>
                    <th>Action</th>
                </thead>
                <tbody>
                @foreach($nlp_katadasars as $nlp_katadasar)
                    <tr>
                        <td>
                            <a href="{!! route('nlp_katadasars.edit', [$nlp_katadasar->id]) !!}">{{ $nlp_katadasar->katadasar }}</a>
                        </td>
                        <td>
                            <a>{{ $nlp_katadasar->tipe_katadasar }}</a>
                        </td>
                        <!-- <td>
                            <a href="{!! route('nlp_katadasars.edit', [$nlp_katadasar->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                            <form method="post" action="{!! route('nlp_katadasars.destroy', [$nlp_katadasar->id]) !!}">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                                <button type="submit" onclick="return confirm('Are you sure you want to delete this nlp_katadasar?')"><i class="fa fa-trash"></i> Delete</button>
                            </form>
                        </td> -->
                        <td>
                            <a style="margin:1px;" class="btn btn-warning btn-xs pull-right raw-margin-right-16" href="{!! route('nlp_katadasars.edit', [$nlp_katadasar->id]) !!}"><span class="fa fa-pencil"></span> Ubah</a>
                             <form method="post" action="{!! route('nlp_katadasars.destroy', [$nlp_katadasar->id]) !!}">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                            <button style="margin:1px;" class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this nlp_katadasar?')"><i class="fa fa-trash"></i> Hapus</button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="row">
                {!! $nlp_katadasars; !!}
            </div>
        @endif
    </div>
</div>
@stop
@section('javascript')
<script type="text/javascript">
    $(document).ready( function () {
    $('.display').DataTable();
    } );
</script>
@stop

resources/views/nlp_katadasars/show.blade.php
<div class="container">

    <!-- Put fields here -->

</div>